import fs from 'fs';

const replacements = {
  "l1_2.ts": "Membangun identitas yang kuat (الْهُوِيَّةُ) adalah pilar utama dalam pergaulan bahasa Arab. Di Bab 2 ini, Anda tidak sekadar belajar menghafal nama dan profesi, melainkan sedang merajut identitas lengkap—mulai dari diri sendiri, keluarga, hingga rekan profesional—yang akan mendefinisikan siapa Anda di mata dunia. Jika Anda merasa belajar bahasa baru itu berat, bersiaplah untuk takjub, karena bahasa Arab sangatlah sistematis dan mudah ditebak polanya!\\n\\nMenguasai bahasa Arab melampaui sekadar hafalan kosakata; ini tentang menyelami kaidah 'Keselarasan Gender' (Mudzakkar & Muannats) yang menjiwai setiap detak pembicaraan. Anda akan dilatih menguasai kosakata inti dan variasi kalimat yang dirancang untuk melatih insting bahasa Anda secara natural tanpa harus berpikir keras. Ini adalah tentang menanamkan kepercayaan diri, di mana setiap kalimat yang Anda ucapkan adalah pernyataan jati diri yang kokoh, penuh kebanggaan, dan bukti betapa mudahnya menaklukkan bahasa Al-Qur'an ini.",
  "l1_3.ts": "Membangun ikatan dan silsilah (الْأُسْرَةُ) adalah fondasi terkuat dalam masyarakat Arab. Di Bab 3 ini, Anda tidak sekadar menghafal nama-nama kerabat, melainkan sedang menyelami struktur sosial dan emosional yang membentuk inti peradaban. Banyak yang mengira merangkai kata kepemilikan itu rumit, padahal bahasa Arab menawarkannya dengan cara yang jauh lebih mudah dan ringkas dibandingkan bahasa lain.\\n\\nLebih dari sekadar kosakata, bab ini akan menyingkap salah satu rahasia arsitektur bahasa Arab yang paling elegan dan praktis: Idhafah (Frasa Kepemilikan). Ini adalah seni menyatukan dua entitas menjadi satu kesatuan makna yang utuh dan presisi, tanpa memerlukan kata penghubung tambahan yang bertele-tele. Menguasai Idhafah berarti Anda mulai berpikir efisien layaknya penutur asli, dan Anda akan menyadari betapa mudahnya aturan ini diaplikasikan. Bersiaplah merangkai struktur kata yang memukau dengan sangat gampang, karena setiap anggota keluarga yang Anda kenal kini akan terikat oleh kaidah tata bahasa yang sekuat ikatan darah itu sendiri.",
  "l1_4.ts": "Waktu (الزَّمَان) adalah napas kehidupan, amanah ilahi yang nilainya jauh melampaui gemerlap emas dan perak. Dalam tradisi Arab yang luhur, waktu diibaratkan sebagai pedang yang terhunus—ia adalah anugerah sekaligus tantangan besar bagi mereka yang lalai. Bab 4 ini bukan sekadar kelas tentang angka dan durasi, melainkan sebuah medan latihan untuk membuktikan bahwa angka dan waktu dalam bahasa Arab ternyata sangat mudah dipahami polanya.\\n\\nMenguasai bahasa Arab tentang waktu berarti Anda sedang membangun komunikasi taktis tingkat tinggi untuk mengatur ritme ibadah dan aktivitas duniawi dengan presisi. Dengan kosakata progresif yang telah dikurasi secara mendalam, Anda tidak lagi sekadar melihat jam, tetapi Anda sedang belajar bagaimana mendayagunakan bahasa secara efisien. Jangan khawatir dengan mitos bahwa berhitung dalam bahasa Arab itu memusingkan; begitu Anda tahu pola sederhananya, semuanya akan mengalir otomatis. Mari kita mulai bab ini dengan tekad baja, nikmati kemudahannya, dan saksikan bagaimana Anda berubah menjadi seseorang yang 'menaklukkan waktu' dengan keanggunan bahasa Arab!",
  "l1_5.ts": "Pertemuan pertama adalah gerbang ukhuwah, sebuah titik awal di mana hati dan lisan bertaut merajut ikatan baru. Dalam peradaban Arab dan Islam, sapaan bukanlah sekadar basa-basi sosial, melainkan sebuah doa keselamatan, rahmat, dan keberkahan yang dilangitkan untuk sesama. Bab 5 ini akan menunjukkan betapa mudah dan alaminya membuka percakapan menggunakan bahasa Arab yang memikat hati.\\n\\nMenguasai sapaan (التَّحِيَّة) dan perkenalan (التَّعَارُف) berarti Anda memegang kunci utama untuk melebur ke dalam dunia penutur asli. Melalui kosakata pilihan yang meliputi salam, perkenalan, hingga kata tanya fundamental, Anda akan takjub betapa cepatnya Anda bisa membangun inisiatif percakapan bermakna tanpa harus menghafal aturan grammar yang berat. Semuanya tersusun secara logis dan sangat mudah diikuti, menjadi fondasi penting untuk menavigasi setiap dialog baru.\\n\\nSetiap kata yang Anda ucapkan adalah jembatan menuju hati pendengarnya. Mari kita masuki bab ini dengan antusiasme tinggi, pelajari struktur tanyanya yang praktis, dan buktikan sendiri bahwa berbicara bahasa Arab itu tidak sesulit yang dibayangkan. Percakapan hebat pertama Anda bermula dari langkah mudah di sini!",
  "l1_6.ts": "Makanan dan minuman bukan sekadar kebutuhan fisik, melainkan anugerah yang patut disyukuri. Dalam tradisi Arab, tata krama makan dan menghargai rezeki adalah cerminan dari akhlak mulia. Bab ini akan membuka pintu bagi Anda untuk menyelami kelezatan kosakata kuliner Arab, dan akan membuktikan bahwa memesan makanan atau mengekspresikan rasa dalam bahasa Arab sangatlah mudah dan menyenangkan.\\n\\nAnda akan belajar lebih dari sekadar nama-nama hidangan, tetapi juga memahami rahasia kecil bahasa Arab: Isim Nakirah dan Ma'rifah (Indefinit dan Definit). Ini hanyalah soal menambahkan 'Alif Lam' (ال) di awal kata! Sangat sederhana, bukan? Aturan praktis ini adalah rahasia untuk membedakan antara menyebut 'sebuah roti' secara umum, dengan 'roti itu' yang spesifik di hadapan Anda, membangun logika kalimat yang tajam dan akurat tanpa kerumitan berarti.\\n\\nSetiap suapan ilmu yang Anda dapatkan di sini adalah persiapan praktis untuk percakapan nyata, entah saat memesan kopi di Kairo atau menyantap nasi di Dubai. Mari masuki bab ini dengan rasa lapar akan ilmu, nikmati betapa gampangnya menguasai setiap strukturnya, dan rasakan kepuasan saat Anda mampu berkomunikasi dengan presisi. Bismillah, mari kita mulai hidangan bahasa yang ringan dan lezat ini!",
  "l1_7.ts": "Alam semesta adalah lembaran ayat-ayat Allah yang tak tertulis, di mana setiap gunung yang menjulang dan burung yang beterbangan membawa pesan kebesaran-Nya. Mempelajari kosakata alam (الطَّبِيعَةُ) dalam bahasa Arab akan membawa Anda pada kepekaan luar biasa terhadap ciptaan-Nya. Dan tahukah Anda? Menyebutkan nama-nama keindahan alam ini sangatlah ringan di lisan dan mudah diingat!\\n\\nDi bab ke-7 ini, keistimewaan luar biasa menanti Anda: 'Palet Warna Bahasa Arab'. Anda akan mempelajari satu rumus ajaib (وَزْنُ أَفْعَلَ - فَعْلَاءُ) yang mengatur hampir seluruh kata sifat warna dan fisik. Hanya dengan memahami satu pola sederhana ini, Anda langsung bisa menguasai semua kosakata warna tanpa harus menghafal mati! Bahasa Arab terbukti memiliki pola matematis yang membuat belajar menjadi berkali-kali lipat lebih mudah.\\n\\nKuasailah pola cerdas ini, maka Anda tidak hanya bisa mengatakan 'langit', tapi Anda bisa melukisnya dengan indah: 'Langit yang biru' (السَّمَاءُ الزَّرْقَاءُ). Mari kita bertadabbur alam melalui kacamata bahasa Arab, nikmati kemudahan polanya, dan jadikan setiap kosakata baru sebagai bentuk tasbih yang mengalir lancar dari lisan kita. Selamat mengeksplorasi!",
  "l1_8.ts": "Mampu bertanya dan menunjukkan arah adalah salah satu kemampuan bertahan hidup yang paling penting, sekaligus topik yang paling sering digunakan sehari-hari. Dalam bab 'Al-Amakin' (Tempat) ini, Anda akan dibekali dengan kosakata navigasi kota. Banyak pemula takut dengan grammar, tapi di bab ini Anda akan menyadari betapa sederhananya aturan penunjuk arah dan tempat dalam bahasa Arab!\\n\\nInti tata bahasa dari bab ini adalah 'Preposisi' (Huruf Jar) dan 'Keterangan Tempat' (Zharaf Makan). Keduanya adalah kunci merangkai kalimat arah. Aturan emasnya luar biasa gampang: 'Kata benda yang jatuh setelah preposisi atau keterangan tempat selalu diakhiri harakat Kasrah (garis bawah)'. Ya, hanya dengan satu aturan mutlak ini, struktur kalimat Anda dijamin 100% benar layaknya orang Arab asli!\\n\\nMari kita mulai perjalanan ini. Dengan pola yang begitu mudah ditebak dan aturan yang super simpel ini, dipastikan Anda tidak akan pernah tersesat lagi di jalanan Timur Tengah maupun dalam menyusun kalimat bahasa Arab!",
  "l1_9.ts": "Maa Syaa Allah, selamat! Anda telah tiba di gerbang puncak Level 1 Al-Mubtadi. Ini adalah bukti nyata bahwa bahasa Arab tidaklah sesulit yang dibayangkan banyak orang. Anda telah menaklukkan 8 bab dengan luar biasa—mulai dari dasar kata tunjuk, keluarga, waktu, hingga navigasi kota—semuanya menggunakan logika pola bahasa Arab yang sangat sederhana dan memukau. Kemenangan Anda hingga titik ini menegaskan bahwa siapapun, dengan metode yang tepat, dapat menguasai bahasa Al-Qur'an ini dengan mudah dan menyenangkan!\\n\\nDi Bab 9: Imtihan Al-Mubtadi (Ujian Akhir) ini, Anda akan merayakan seluruh pemahaman yang telah Anda kumpulkan. Jangan merasa tegang; anggaplah ini sebagai panggung kehormatan untuk menampilkan betapa jauh Anda telah melangkah dengan mudahnya. Hadapi setiap soal dengan senyuman dan keyakinan, karena Anda sudah memiliki semua kuncinya di genggaman Anda. Sukses di ujian ini adalah tiket emas menuju petualangan yang lebih menakjubkan di Level 2!\\n\\nUjian komprehensif ini mencakup:\\n✅ Bab 1: Kosakata Dasar & Kata Tunjuk\\n✅ Bab 2: Identitas Diri & Profesi\\n✅ Bab 3: Keluarga & Idhafah\\n✅ Bab 4: Waktu & Angka\\n✅ Bab 5: Salam & Kata Tanya\\n✅ Bab 6: Makanan & Nakirah-Ma'rifah\\n✅ Bab 7: Alam & Warna\\n✅ Bab 8: Tempat & Preposisi\\n\\nSyarat lulus: 75% (38/50 soal)\\nHadiah: Sertifikat Level 1 🏆"
};

for (const [file, newContent] of Object.entries(replacements)) {
  const filePath = "src/data/lessons/" + file;
  let data = fs.readFileSync(filePath, 'utf8');
  const regex = /introduction:\s*("[^]*?"|`[^]*?`)/;
  // Properly stringify the new content to handle escaping automatically
  data = data.replace(regex, "introduction: " + JSON.stringify(newContent));
  fs.writeFileSync(filePath, data);
  console.log("Updated " + file);
}
